# Generated by Django 4.1.3 on 2022-11-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Category title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Product amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='products.category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_shop', to='products.shop', verbose_name='Product shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Product title'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Sale amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sale date and time'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_product', to='products.product', verbose_name='Sale product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Shop address'),
        ),
    ]
